OnlineOrderPortal/Models/ErrorViewModel.cs
using System;

namespace OnlineOrderPortal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OnlineOrderPortal/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineOrderPortal.Data.Models;
using OnlineOrderPortal.Models;
using RestSharp;

namespace OnlineOrderPortal.Controllers
{
    public class CustomerController : Controller
    {
        //  public IActionResult Index()
        // {
        //    return View();
        // }

        public IActionResult New()
        {
            return this.View(new Customer());
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            var client = new RestClient("https://localhost:44350");
            var request = new RestRequest("api/customer/CreateCustomer", Method.POST);
            request.AddJsonBody(new
            {
                Name = customer.Name,
                Email = customer.Email
            });
            var response = client.Execute(request);
            return this.Redirect("New");
        }

        [HttpGet]
        public IActionResult GetCustomersWithoutOrders()
        {
            var resultCustomersList = new List<Customer>();

            var client = new RestClient("https://localhost:44350");
            var request = new RestRequest("api/customer/GetCustomersWithoutOrder", Method.GET);
            
            var response = client.Execute(request);
            var json =  response.Content;
            resultCustomersList = JsonConvert.DeserializeObject<List<Customer>>(response.Content);
            return this.View("Index", resultCustomersList);
        }
        
        
    }
}

OnlineOrderPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OnlineOrderPortal.Models;

namespace OnlineOrderPortal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineOrderPortal/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineOrderPortal.Data;
using OnlineOrderPortal.Data.Models;
using RestSharp;

namespace OnlineOrderPortal.Controllers
{
    public class OrderController : Controller
    {
        private OnlineOrderPortalDataContext dataContext;

        public OrderController(OnlineOrderPortalDataContext dataContext)
        {
            this.dataContext = dataContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetCustomerOrder(string customerName)
        {
            var client = new RestClient("https://localhost:44350");
            var request = new RestRequest("api/order/GetCustomerOrder?customerName="+customerName, Method.GET);
            
            var response = client.Execute(request);
            var json = response.Content;
            var resultOrderList = JsonConvert.DeserializeObject<List<Order>>(response.Content);
            return this.PartialView("OrderResultPartial", resultOrderList);
        }

        public IActionResult AddOrder()
        {
            return this.View("AddOrder");
        }

        [HttpPost]
        public IActionResult CreateOrder(string customerName, int price)
        {
            var client = new RestClient("https://localhost:44350");
            var request = new RestRequest("api/order/CreateOrder", Method.POST);
            request.AddJsonBody(new
            {
                Price = price,
                CreatedDate = DateTime.Now,
                customerId = this.dataContext.Customers.SingleOrDefault(o => o.Name == customerName).Id
            });
            var response = client.Execute(request);
            var json = response.Content;
            var resultOrderList = JsonConvert.DeserializeObject<List<Order>>(response.Content);
            return this.PartialView("OrderResultPartial", resultOrderList);

        }

    }
}

OnlineOrderPortal/Views/Customer/Index.cshtml
@using OnlineOrderPortal.Data.Models
@model List<OnlineOrderPortal.Data.Models.Customer>
@{
    ViewData["Title"] = "Index";
}

@section Scripts
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
}

<h1>
    Customer Details
</h1>

<div class="col-md-12" id="tableParentDiv" style="display: table">
    <table class="table" id="customerTable">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(result => customer.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(result => customer.Email)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

OnlineOrderPortal/Views/Customer/New.cshtml
@model OnlineOrderPortal.Data.Models.Customer

@{
    ViewData["Title"] = "New";
}

<h1>New</h1>

<form id="newCustomerForm" asp-action="Create" asp-controller="Customer">
    <div class="form-group">
        <label>Name:</label>
        <input type="text" id="customerName" asp-for="Name" />
    </div>
    <div class="form-group">
        <label>Email:</label>
        <input type="text" id="email" asp-for="Email" />
    </div>
    <button name="button" type="submit" class="btn btn-primary" id="createCustomerButton">Create</button>
</form>

OnlineOrderPortal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="card-deck ">
        <a class="card text-center p-1" asp-controller="Customer" asp-action="New">
            <div class="card-body">
                <h5 class="card-text"></h5>
                <h5 class="card-title">Add Customer</h5>
            </div>
        </a>

        <a class="card text-center p-1" asp-controller="Customer" asp-action="GetCustomersWithoutOrders">
            <div class="card-body ">
                <h5 class="card-text"></h5>
                <h5 class="card-title">Get Customer Without Orders</h5>
            </div>
        </a>
        <a class="card text-center p-1" asp-controller="Order" asp-action="Index">
            <div class="card-body">
                <h5 class="card-text"></h5>
                <h5 class="card-title">Get Orders</h5>
            </div>
        </a>
    </div>
</div>

OnlineOrderPortal/Views/Order/Index.cshtml
@model List<OnlineOrderPortal.Data.Models.Order>
@{
    ViewData["Title"] = "Index";
}

@section Scripts
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
        $("#getOrderButton").click(function (e) {
            e.preventDefault();
            console.log("click button");
            var data = {
                customerName: $("#customerNameInput").val().trim()
            };
            $.ajax({
                url: "/Order/GetCustomerOrder",
                data: data,
                type: "get",
                success: function (response) {
                    $("#orderDetailResult").html(response);
                }
            })
        });

        $("#addOrderButton").click(function (e) {
            e.preventDefault();
            console.log("click button");
            var data = {
                customerName: $("#customerNameInput").val().trim(),
                price: $("#priceInput").val().trim()
            };
            $.ajax({
                url: "/Order/CreateOrder",
                data: data,
                type: "post",
                success: function (response) {
                    alert("New order created");
                    $("#orderDetailResult").html(response);
                }
            })
        });
    </script>
}


<h1>Order Details</h1>

<div class="row">
        <div class="col-md-2">
            <form id="getOrderForm">
                <div class="form-group">
                    <label>Customer Name</label>
                    <input id="customerNameInput" type="text">
                    <button type="submit" id="getOrderButton">Get Orders</button>
                </div>
            </form>
            <form id="addOrder">
                <div class="form-group">
                    <label>Price</label>
                    <input id="priceInput" type="number">
                    <button type="submit" id="addOrderButton">Add Order</button>
                </div>
            </form>
        </div>
            <div class="col-md-10" id="orderDetailResult">
    </div>
</div>

OnlineOrderPortal/Views/Order/OrderResultPartial.cshtml
@using OnlineOrderPortal.Data.Models
@model List<OnlineOrderPortal.Data.Models.Order>

@section Scripts
    {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
}



<div class="col-md-12" id="orderTableParentDiv" style="display: table">
    <table class="table" id="orderTable">
        <thead>
            <tr>
                <th scope="col">Price</th>
                <th scope="col">Created Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(result => order.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(result => order.CreatedDate)
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

OnlineOrderPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineOrderPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineOrderPortal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OnlineOrderPortal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>